### ISSUE TITLE
请求代码

### ISSUE THREAD

**Issue by 543509953** [ljllili23/Chinese_rec_GUI#1]
我最近在做毕设想参考一下您的设计，请您能联系一下我吗，我的邮箱是v95172v9517@qq.com
或者您再这下面留一下您的联系方式   万分感谢！！！

**Comment by ljllili23** [comment]
你好，网络设计上只用了一个简单的alexnet的改进，全部的代码都在data文件夹中，两个源文件。你可能需要用较早版本的tensorflow，比如1.4才能顺利跑通。
