### ISSUE TITLE
改进一次识别多个文字

### ISSUE THREAD

**Issue by xubiaolin** [ljllili23/Chinese_rec_GUI#4]
你好,请问你的这个项目如何改进为一次识别多个字符呢?一次一次调用里面的识别函数效率有点低.

**Comment by ljllili23** [comment]
> 你好,请问你的这个项目如何改进为一次识别多个字符呢?一次一次调用里面的识别函数效率有点低.

你的意思是输入字符段图片吗？这个不太好搞，还要做字符定位和切割。

**Comment by xubiaolin** [comment]
我今天修改好了,我这里已经做好了字符定位切割,并且把你的代码修改了一下.输入一张图片可以识别出里面的字体.
